version: "3.7"

services:
  db:
    container_name: "Zozumi"
    image: "postgres"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: webapp_db